### ISSUE TITLE
Update to 2022-02-02_maint-3.8 and 2022-02-02_maint-3.9

### ISSUE THREAD

**Issue by schneider42** [conda-forge/gnuradio-iridium-feedstock#8]
The tags above contain the latest state of gr-iridium and also incorporate the patches in this repo.

I'm not terribly familiar with conda and its build system, I guess it might be a bit easier for you.

**Comment by ryanvolz** [comment]
I can bump them pretty easily, thanks for pointing them out! I'm a little sad that it seems like the conda-forge bot did not pick up the tags, but it's been two days already and it usually would only take a couple hours. I guess it only likes dealing with numeric-only version tags.

**Comment by schneider42** [comment]
Too bad there still are patches needed to get it running under Windows. I should have caught the uneeded include at least...

Regarding tags: I might switch to vx.y.z tags similar to what gr-satellites does. Maybe that will help in the future.

**Comment by ryanvolz** [comment]
Yeah, the include patch is the only thing that I think should go upstream. The other patch, removing the setting of GR_PYTHON_DIR, is only necessary because conda puts Python modules outside of the library prefix on Windows, so I need to set GR_PYTHON_DIR manually anyway to make it install correctly.
